import Link from 'next/link';

export default function Footer() {
  return (
      <footer className="bg-gray-900 text-gray-300 mt-auto border-t border-gray-800">
            <div className="max-w-7xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                              
                                        {/* نبذة عن المتجر */}
                                                  <div>
                                                              <h3 className="text-xl font-bold text-white mb-4">متجرنا الإلكتروني</h3>
                                                                          <p className="text-sm text-gray-400 leading-relaxed">
                                                                                        منصتك الأولى للتسوق الذكي. نوفر لك أفضل المنتجات بأعلى جودة مع دعم للتوصيل السريع لجميع المناطق.
                                                                                                    </p>
                                                                                                              </div>

                                                                                                                        {/* روابط سريعة */}
                                                                                                                                  <div>
                                                                                                                                              <h4 className="text-md font-semibold text-white mb-4">روابط هامة</h4>
                                                                                                                                                          <ul className="space-y-2 text-sm">
                                                                                                                                                                        <li>
                                                                                                                                                                                        <Link href="/categories" className="hover:text-white transition">جميع المنتجات</Link>
                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                    <li>
                                                                                                                                                                                                                                    <Link href="/cart" className="hover:text-white transition">عربة التسوق</Link>
                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                <Link href="/checkout" className="hover:text-white transition">إتمام الشراء</Link>
                                                                                                                                                                                                                                                                                              </li>
                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                              {/* خدمة العملاء */}
                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                    <h4 className="text-md font-semibold text-white mb-4">الدعم والمساعدة</h4>
                                                                                                                                                                                                                                                                                                                                                                <ul className="space-y-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                              <li>
                                                                                                                                                                                                                                                                                                                                                                                              <Link href="#" className="hover:text-white transition">الأسئلة الشائعة</Link>
                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                          <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="#" className="hover:text-white transition">سياسة الشحن والاسترجاع</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link href="#" className="hover:text-white transition">الشروط والأحكام</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* التواصل الاجتماعي والنشرة البريدية */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h4 className="text-md font-semibold text-white mb-4">تواصل معنا</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm text-gray-400 mb-3">اشترك للحصول على أحدث العروض والخصومات.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <form onSubmit={(e) => e.preventDefault()} className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="بريدك الإلكتروني"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="bg-gray-800 text-white text-sm px-3 py-2 rounded border border-gray-700 focus:outline-none focus:border-blue-500 w-full"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-blue-600 text-white px-4 py-2 rounded text-sm font-semibold hover:bg-blue-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          اشتراك
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* حقوق النشر */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="border-t border-gray-800 mt-8 pt-6 text-center text-xs text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>© {new Date().getFullYear()} جميع الحقوق محفوظة لـ متجرنا الإلكتروني.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    