'use client';

import Link from 'next/link';
import { useCart } from '@/context/CartContext';
import { useState } from 'react';

export default function Header() {
  const { cart } = useCart();
    const [searchQuery, setSearchQuery] = useState('');

      const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);

        const handleSearch = (e: React.FormEvent) => {
            e.preventDefault();
                if (searchQuery.trim()) {
                      window.location.href = `/categories?search=${encodeURIComponent(searchQuery)}`;
                          }
                            };

                              return (
                                  <header className="bg-white shadow-sm sticky top-0 z-50 border-b border-gray-100">
                                        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                                                <div className="flex items-center justify-between h-16 gap-4">
                                                          
                                                                    {/* شعار المتجر */}
                                                                              <div className="flex-shrink-0">
                                                                                          <Link href="/" className="text-2xl font-bold text-blue-600 tracking-wide">
                                                                                                        متجرنا
                                                                                                                    </Link>
                                                                                                                              </div>

                                                                                                                                        {/* شريط البحث المطور المجهز للـ SEO و المعالجة المباشرة */}
                                                                                                                                                  <form onSubmit={handleSearch} className="flex-1 max-w-lg hidden md:flex">
                                                                                                                                                              <div className="relative w-full">
                                                                                                                                                                            <input
                                                                                                                                                                                            type="text"
                                                                                                                                                                                                            value={searchQuery}
                                                                                                                                                                                                                            onChange={(e) => setSearchQuery(e.target.value)}
                                                                                                                                                                                                                                            placeholder="ابحث عن منتج، كود، أو تصنيف..."
                                                                                                                                                                                                                                                            className="w-full bg-gray-50 border border-gray-300 rounded-lg py-2 pr-10 pl-4 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:bg-white transition"
                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                        type="submit"
                                                                                                                                                                                                                                                                                                                        className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-blue-600"
                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                                                                                                                                                                                                                                                                                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                                                                                                                                                                                                                                                                                                                                                                                        </svg>
                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* روابط التنقل والوصول السريع */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-center gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/categories" className="text-gray-700 hover:text-blue-600 font-medium text-sm hidden sm:block">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          التصنيفات
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/auth/login" className="text-gray-700 hover:text-blue-600 font-medium text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                حسابي
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* أيقونة السلة مع عداد المنتجات */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/cart" className="relative flex items-center text-gray-700 hover:text-blue-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {totalItems > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="absolute -top-2 -right-2 bg-red-500 text-white text-xs font-bold w-5 h-5 rounded-full flex items-center justify-center animate-pulse">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {totalItems}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        